### ISSUE TITLE
please use at least 3 dashes

### ISSUE THREAD

**Issue by ysiw** [wooorm/markdown-table#17]
Many markdown software requires at least 3 dashes when processing table

**Comment by wooorm** [comment]
Could you explain why?

**Comment by ysiw** [comment]
FYI
search "3 dashes" in this page https://gitlab.com/gitlab-org/gitlab-foss/-/issues/26786

**Comment by ysiw** [comment]
Practicly, it is ok for `---` `:--` `:-:` and `--:`, but not for `-` `:-` `-:`

**Comment by wooorm** [comment]
GitHub, who [maintains](https://github.github.com/gfm/#tables-extension-) the “standard” for markdown tables, had stopped needing 3 characters, since [March 14, 2017](https://github.blog/2017-03-14-a-formal-spec-for-github-markdown/).
We used to support the previous behavior, [but dropped it recently in 2.0.0](https://github.com/wooorm/markdown-table/releases/tag/2.0.0).
I have no plans on supporting something that hasn’t been needed for three years already. you could either a) use an older version of this project, b) suggest that GitLab fixes this, their source is outdated, or c) kinda hackish, but use a `stringLength` that returns at least 3!
