### ISSUE TITLE
ESM not working as expected

### ISSUE THREAD

**Issue by seancdavis** [wooorm/markdown-table#22]
Tried to upgrade to v3 in a project that is using TypeScript to import this file and I'm seeing the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../node_modules/markdown-table/index.js
require() of ES modules is not supported.
```

I played around with renaming the main file with `.cjs` and `.mjs` and ran into other issues.

Running Node v15.11.0

**Comment by wooorm** [comment]
Heya. You’re the first to be hit by this. Expect more to come over the following months tho.

TL:DR; don’t update to ESM yet if you don’t want to. But it’s time to start thinking about moving to actual ESM instead of faux-ESM/CJS.

Related:
- https://twitter.com/sindresorhus/status/1349294527350149121
- https://twitter.com/kentcdodds/status/1369803853005209602
- https://github.com/unifiedjs/unified/issues/121

**Comment by fantapop** [comment]
Is the crux of the issue here that markdown-table is esm only and the typescript project is compiling down to commonjs before executing?

**Comment by wooorm** [comment]
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c for more info about how to use TS with ESM.
